### ISSUE TITLE
Secondary addressing?

### ISSUE THREAD

**Issue by mpictor** [gotmc/prologix#1]
Hi,

It looks like this project doesn't support secondary addressing.

This is needed for certain devices, such as the Tek 7912AD.

It is supported by prologix, and Twilight-Logic is looking into support in the prologix-compatible [Twilight-Logic/AR488](https://github.com/Twilight-Logic/AR488).

For primary (PAD) `20` and secondary (SAD) `2`, you would send `++addr 20 98` where 98 is SAD + 96. I'm not sure where 96 comes from but I've seen it a number of places.

I may try adding support; any thoughts on how you'd like it to look?

**Comment by matthewrankin** [comment]
In order to avoid a breaking change, I added `opts` as an optional variadic parameter to the end of `NewController`. In order to set the secondary address use the following:

```go
// Open virtual comm port.
vcp, err := vcp.NewVCP("/dev/tty.usbserial001")
if err != nil {
	log.Fatal(err)
}

// Create a new GPIB controller using the aforementioned serial port and
// communicating with the instrument at GPIB primary address 20 and
// secondary address 98.
gpib, err := prologix.NewController(vcp, 20, false, WithSecondaryAddress(98))
if err != nil {
	log.Fatalf("NewController error: %s", err)
}
```

**Comment by mpictor** [comment]
Nice, thanks!

Haven't had a chance to try it yet - I'm fiddling with TwilightLogic's arduino code, trying to determine if the SAD support they've added is to blame or if the 7912 is.
